### ISSUE TITLE
Error 'undefined method `encode' for nil:NilClass' if empty worksheet name

### ISSUE THREAD

**Issue by Yegorov** [caxlsx/caxlsx#102]
Hello! I got error `undefined method `encode' for nil:NilClass (NoMethodError)` if set worksheet name to empty string.
Example:
```ruby
require 'caxlsx'

pkg = Axlsx::Package.new do |pk|
  pk.workbook.add_worksheet(name: "") do |sheet| # <-- ok, if name not empty
    sheet.add_row ["1", "2"]
  end
end

pkg.to_stream.string
```

Traceback
```
Traceback (most recent call last):                                                                                      
        32: from /home/artem/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'                              
        31: from /home/artem/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'                                
        30: from /home/artem/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'                                                
        29: from /home/artem/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'                                                  
        28: from /home/artem/.rvm/gems/ruby-2.6.5/gems/irb-1.3.5/exe/irb:11:in `<top (required)>'                       
        11: from (irb):2:in `<main>'                                                                                    
        10: from (irb):2:in `new'                                                                                       
         9: from /home/artem/.rvm/gems/ruby-2.6.5/gems/caxlsx-3.1.0/lib/axlsx/package.rb:29:in `initialize'             
         8: from (irb):3:in `block in <main>'                                                                           
         7: from /home/artem/.rvm/gems/ruby-2.6.5/gems/caxlsx-3.1.0/lib/axlsx/workbook/workbook.rb:269:in `add_workshee$
'                                                                                                                       
         6: from /home/artem/.rvm/gems/ruby-2.6.5/gems/caxlsx-3.1.0/lib/axlsx/workbook/workbook.rb:269:in `new'         
         5: from /home/artem/.rvm/gems/ruby-2.6.5/gems/caxlsx-3.1.0/lib/axlsx/workbook/worksheet/worksheet.rb:21:in `in$tialize'
         4: from /home/artem/.rvm/gems/ruby-2.6.5/gems/caxlsx-3.1.0/lib/axlsx/util/options_parser.rb:10:in `parse_optio$s'
         3: from /home/artem/.rvm/gems/ruby-2.6.5/gems/caxlsx-3.1.0/lib/axlsx/util/options_parser.rb:10:in `each'
         2: from /home/artem/.rvm/gems/ruby-2.6.5/gems/caxlsx-3.1.0/lib/axlsx/util/options_parser.rb:12:in `block in pa$se_options'
         1: from /home/artem/.rvm/gems/ruby-2.6.5/gems/caxlsx-3.1.0/lib/axlsx/workbook/worksheet/worksheet.rb:309:in `n$me='
/home/artem/.rvm/gems/ruby-2.6.5/gems/caxlsx-3.1.0/lib/axlsx/workbook/worksheet/worksheet.rb:671:in `validate_sheet_nam$': undefined method `encode' for nil:NilClass (NoMethodError)
```

I use:
* ruby 2.6.5
* caxlsx 3.1.0

I think we need to handle this exceptional example.
Error in second [`encode("utf-16")`](https://github.com/caxlsx/caxlsx/blob/8d55f0d2ad3c5e4f4c6e9be1cf1e7b065fc25e49/lib/axlsx/workbook/worksheet/worksheet.rb#L671)
I can send PR for fix this error.

**Comment by noniq** [comment]
Does Excel allow empty worksheet names? (That is, do we need to fix the validator so that it forbids empty strings, or do we need to fix the error that happens when trying to encode an empty string?)

**Comment by straydogstudio** [comment]
The excel I have does not allow empty worksheet names. But I don't know what the standard is. I suggest we improve the message.

**Comment by simi** [comment]
Can anyone provide example file?

Dne pá 10. 12. 2021 1:48 uživatel github-actions[bot] <
***@***.***> napsal:

**Comment by straydogstudio** [comment]
@simi I imagine we just need to generate a more meaningful error.

**Comment by simi** [comment]
@Yegorov sorry for the delay, can you check https://github.com/caxlsx/caxlsx/pull/116 and test this solves your problem?

**Comment by Yegorov** [comment]
> @Yegorov sorry for the delay, can you check #116 and test this solves your problem?

Ok, thanks for fix.
