### ISSUE TITLE
Package#to_stream does not work in 3.2.0

### ISSUE THREAD

**Issue by vlakre** [caxlsx/caxlsx#138]
Hello 👋 

I've noticed that since the update to v3.2.0, `Package#to_stream` method stopped working.
I suspect the issue is due to this change:

v3.2.0
```ruby
package = Axlsx::Package.new
package.to_stream.external_encoding
=> #<Encoding:ASCII-8BIT>
```

While in the previous version, the encoding was UTF-8:

```ruby
package = Axlsx::Package.new
package.to_stream.external_encoding
=> #<Encoding:UTF-8>
```

When I try to write the stream to the file (as per the docs) I get the following error:
```
Encoding::UndefinedConversionError: "\xEC" from ASCII-8BIT to UTF-8
```

Since this issue was a breaking change for me, I believe it should've been stated as such in the Changelog.md

Btw I've switched to using `Package#serialize` in the meantime and it is working. 🙂

**Comment by kiskoza** [comment]
[This PR](https://github.com/caxlsx/caxlsx/pull/120) changed how we handle the to_stream method. I'm going to investigate the issue

**Comment by kiskoza** [comment]
hi @vlakre . I ran the [Stream example](https://github.com/caxlsx/caxlsx/blob/v3.2.0/examples/stream_example.md) and wrote the stream to a file successfully using Caxlsx 3.2.0 and Ruby 3.0.2. Could you provide more information or a code snippet to reproduce your issue?

**Comment by vlakre** [comment]
hi @kiskoza 
interesting 🙂 
I'm using ruby 3.1.0 and Caxlsx 3.2.0 and this code snippet produces an error:

```ruby
p = Axlsx::Package.new
stream = p.to_stream
File.open('stream_example.xlsx', 'w') { |f| f.write(stream.read) }

=> Encoding::UndefinedConversionError: "\xEC" from ASCII-8BIT to UTF-8
```

I get the error even if I add sheets/rows to the workbook like in the example you've provided.

**Comment by straydogstudio** [comment]
@kiskoza Perhaps something else in the gemfile is causing issues?

**Comment by noniq** [comment]
Have you tried opening the file in binary mode (`File.open('stream_example.xlsx', 'wb')`)?

**Comment by shanecav84** [comment]
Forcing UTF-8 worked for me. `@package.to_stream.read.force_encoding('UTF-8')`

**Comment by noniq** [comment]
@vlakre I can't reproduce this using Ruby 3.1.2 and caxlsx 3.2.0 running on macOS – are you running on Windows?

**Comment by vlakre** [comment]
Hi @noniq 
No, I'm using M1 Mac, macOS Monterey 12.3.
But this also happened on our production machine, which is on Ubuntu 18.4

**Comment by pjar** [comment]
I have the same issue - quite simple rails app. Ruby 3.1.2, Rails 7.0.3, M1 Mac, local env with docker, macOS Monterey 12.4
Forcing encoding worked for me too.

**Comment by noniq** [comment]
@pjar Could you try the test script I posted above and post its output here?

**Comment by timdiggins** [comment]
FYI Running the [caxslx-rails testsuite](https://github.com/caxlsx/caxlsx_rails/blob/master/spec/ci.rb) against 3.2.0 (on MacOS) produces a set of failures which look like they are related to this problem, e.g.

```
  1) Caxlsx request downloads an excel file with partial
     Failure/Error: File.open('/tmp/caxlsx_temp.xlsx', 'w') {|f| f.write(page.source) }

     Encoding::UndefinedConversionError:
       "\xEC" from ASCII-8BIT to UTF-8
     # ./spec/axlsx_request_spec.rb:76:in `write'
     # ./spec/axlsx_request_spec.rb:76:in `block (3 levels) in <top (required)>'
     # ./spec/axlsx_request_spec.rb:76:in `open'
     # ./spec/axlsx_request_spec.rb:76:in `block (2 levels) in <top (required)>'
 ```

**Comment by westonganger** [comment]
[axlsx_styler](https://github.com/axlsx-styler-gem/axlsx_styler) builds are also failing with `caxlsx@3.2.0` because of this same thing

**Comment by noniq** [comment]
What still baffles me is that the minimal test case I posted in https://github.com/caxlsx/caxlsx/issues/138#issuecomment-1180293952 seems not to trigger this bug (have all of you tried it out)?

**Comment by westonganger** [comment]
I have not yet tried it out (no more time tonight). But I suspect a minimal example wouldnt reproduce it.

Its likely that the encoding is failing on a much more inner object, maybe one of the styles or something.

This is the tests that fails on axlsx_styler

```ruby
  def test_works_without_apply_styles_to_stream
    filename = 'without_apply_styles_to_stream'
    assert_nil @workbook.styles_applied
    @workbook.add_worksheet do |sheet|
      sheet.add_row ['A1', 'B1']
      sheet.add_style 'A1:B1', b: true
    end
    to_stream(filename)
    assert_equal 1, @workbook.styles.style_index.count
  end
```

**Comment by westonganger** [comment]
Ok so I just checked and noticed 3.2.0 worked fine in my other gem `spreadsheet_architect` which also uses `to_stream`

In my test cases there, I noted that I used `File.open(filename, 'wb'`. So I tried using `wb` instead of `w` within the axlsx_styler test suite and that resolved the issue for my purposes.

**Comment by noniq** [comment]
I added a commit that makes sure all examples use binary mode when writing the stream to a file. I think this should be enough – in the end, this is not about caxlsx but about how to use `File.write`.
